---
stages:
  - build_and_push
services:
  - docker:23.0.0-dind

.common_build:
  stage: build_and_push
  before_script:
    - docker-compose build
    - docker images

build_without_push:
  stage: build_and_push
  extends:
    - .common_build
  script:
    - docker-compose up -d
    - echo "Show local images"
    - sleep 5
    - docker ps -a
    - docker-compose down
  except:
    - master
    - main

build_and_push:
  stage: build_and_push
  extends:
    - .common_build
  script:
    - docker-compose up -d
    - echo "Show local images"
    - sleep 5
    - docker ps -a
    - docker-compose down
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_LOGIN" --password-stdin "$DOCKER_REGISTRY_URL"
    - docker-compose push
    - docker tag ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_DIR}/${PROJECT_NAME}:${IMAGE_TAG} ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_DIR}/${PROJECT_NAME}:${DOCKER_VERSION}
    - docker push ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_DIR}/${PROJECT_NAME}:${DOCKER_VERSION}
  only:
    - master
    - main
